SBOM Report integration in File Page
appknox/irene pull request #1229
Opened 2023-06-16 10:46 UTC by Yibaebi

2023-06-16 11:24 UTC, future-pirate-king requested changes

2023-06-16 11:24 UTC, future-pirate-king commented on app/components/file/report-drawer/sbom-reports/sample/index.ts
> +  REPORT_ENDPOINT = 'v2/sample_sbom/sample-reports';
this should be property in environment variable

2023-06-16 11:51 UTC, Yibaebi commented on app/adapters/file.ts
> +    const sbFileRes = await this.network.request(URL);
@cosmosgenius Mentioned that we should slowly migrate to the network service.

2023-06-16 12:03 UTC, Yibaebi commented on app/adapters/file.ts
> +    const sbFileRes = await this.network.request(URL);
There is no problem with the Ajax service.

2023-06-21 10:51 UTC, cosmosgenius requested changes

2023-06-21 10:51 UTC, cosmosgenius commented on app/adapters/file.ts
> +    const sbFileRes = await this.network.request(URL);
wait here i think the best is `ajax` and not use the network... ajax is better and migration to future ember systems is easier...
Anything model, adapter or store related its better to use `this.ajax` which is not a injected service...
If you are doing a network call for something else like from component directly network is better.

The reason being the custom ajax service is old and not updated... but in store `this.ajax` internal uses fetch and is modern...

2023-07-05 14:18 UTC, future-pirate-king requested changes

2023-07-05 14:18 UTC, future-pirate-king commented on app/components/file/report-drawer/sbom-reports/sample/index.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
let it show warning will help us fix later

2023-07-14 14:41 UTC, cosmosgenius approved these changes

2023-07-14 14:41 UTC, merged