fix organization team invitation list resend delete
appknox/irene pull request #1250
Opened 2023-08-29 06:19 UTC by avzz-19

2023-08-29 09:47 UTC, future-pirate-king requested changes

2023-08-29 09:47 UTC, future-pirate-king commented on app/models/organization-team-invitation.ts
> +    );
add new line here

2023-08-29 13:25 UTC, cosmosgenius requested changes

2023-08-29 13:25 UTC, cosmosgenius commented on app/models/organization-team-invitation.ts
> +import OrganizationInvitationModel from './organization-invitation';
This is a bad idea. Even tho the two models look similar it better to keep them separate... As in terms of business logic it is different.

Inheritance is model is bad in general case... unless you are inheriting from abstract class. Lets avoid these

2023-08-29 13:25 UTC, cosmosgenius commented on app/models/organization-team-invitation.ts
> +import OrganizationInvitationModel from './organization-invitation';
Duplicate the code along with tests.

2023-08-31 06:39 UTC, future-pirate-king approved these changes

2023-08-31 09:03 UTC, cosmosgenius approved these changes

2023-08-31 09:03 UTC, merged