material icon migration for login component
appknox/irene pull request #1251
Opened 2023-09-01 08:44 UTC by avzz-19

2023-09-05 05:10 UTC, future-pirate-king requested changes

2023-09-05 05:10 UTC, future-pirate-king commented on app/components/login-component/index.scss
> +    stroke: var(--ak-button-color-primary-contrast-text) !important;
use component specific variable name

2023-09-05 05:10 UTC, future-pirate-king commented on app/styles/_icons.scss
> -.ak-icon-close {
why is this removed ?

2023-09-05 05:16 UTC, avzz-19 commented on app/styles/_icons.scss
> -.ak-icon-close {
duplicate

2023-09-05 06:31 UTC, future-pirate-king commented on app/styles/_component-variables.scss
> +  --ak-spinner-primary-contrast-text: var(--primary-contrast-text)
variable name should start with component name eg: `login-component-button-loader-color`

2023-09-13 05:51 UTC, future-pirate-king approved these changes

2023-09-13 05:59 UTC, merged