main page loader icon migration
appknox/irene pull request #1283
Opened 2023-10-20 12:00 UTC by avzz-19

2023-10-25 16:05 UTC, future-pirate-king requested changes

2023-10-25 16:05 UTC, future-pirate-king commented on tests/integration/components/loading-spinner-test.js
file name should be `main-loader-test.js`

2023-10-26 05:28 UTC, avzz-19 commented on tests/integration/components/loading-spinner-test.js
done

2023-10-28 06:46 UTC, future-pirate-king requested changes

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/main-loader/index.hbs
> +  {{/if}}
use `component` helper to simplify
Eg:
```
{{#let (component this.currentLoaderImage) as |LoaderImage|}}
  <LoaderImage />
{{/let}}
```

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/main-loader/index.hbs
> +  {{!-- <AkLoader::Linear
remove comment

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/main-loader/index.hbs
> +    @progress={{this.dummyPositionIndicator}}
rename this variable to `this.fakeProgress`

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/main-loader/index.ts
> +  @tracked currentLoader = 1;
rename this to `currentLoaderImage`

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/main-loader/index.ts
> +  updateDummyIndicatorTask() {
rename this function to  `generateFakeProgress`

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/main-loader/index.ts
> +  }
clear all intervals in `willDestroy`

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/ak-svg/loader-image1.hbs
rename this file to `main-loader-image1`

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/ak-svg/loader-image2.hbs
rename this file to `main-loader-image2`

2023-10-28 06:46 UTC, future-pirate-king commented on app/components/ak-svg/loader-image3.hbs
rename this file to `main-loader-image3`

2023-10-28 13:36 UTC, future-pirate-king requested changes

2023-10-28 13:36 UTC, future-pirate-king commented on app/components/main-loader/index.ts
> +  }
need to clear intervals in `willDestroy`
```
clearInterval(this.fakeProgressInterval)  // set this variable in `generateFakeProgress`
clearInterval(this.switchImageInterval)  // set this variable in `switchImage`
```

2023-10-28 13:36 UTC, future-pirate-king commented on app/components/main-loader/index.ts
> +      }
clear interval in else block

2023-10-28 13:36 UTC, future-pirate-king commented on app/components/main-loader/index.hbs
> +  main-loader-container
rename to `data-test-main-loader-container`

2023-10-28 13:36 UTC, future-pirate-king commented on app/components/main-loader/index.hbs
> +    main-loader-linear-progress
rename to `data-test-main-loader-linear-progress`

2023-10-28 13:36 UTC, future-pirate-king commented on app/components/main-loader/index.hbs
> +  {{/let}}
add a new line

2023-10-30 06:43 UTC, future-pirate-king requested changes

2023-10-30 06:43 UTC, future-pirate-king commented on tests/integration/components/ak-loader/linear-test.js
> +    assert.dom(linearProgressIndicator).exists();
add new line

2023-10-30 06:43 UTC, future-pirate-king commented on app/components/main-loader/index.ts
> +    super.willDestroy();
add new line

2023-10-30 14:03 UTC, future-pirate-king approved these changes

2023-10-30 14:03 UTC, merged