PD-972: Dast automation scenario UI and Integration
appknox/irene pull request #1306
Opened 2023-12-15 12:35 UTC by Yibaebi

2023-12-20 11:40 UTC, future-pirate-king commented on app/components/project-settings/view-scenario/parameter-item/index.hbs
> +        {{style minWidth='423px'}}
can we round this to 420px

2023-12-20 16:16 UTC, future-pirate-king requested changes

2023-12-20 16:16 UTC, future-pirate-king commented on app/styles/_color.scss
> +  --project-settings-light-background-color: #fbfbfb;
use `--background-light`

2023-12-20 16:16 UTC, future-pirate-king commented on app/styles/_color.scss
> +  --zIndex-clear-btn: 1501;
remove this

2023-12-20 16:16 UTC, future-pirate-king commented on app/styles/_color.scss
> +  --dast-scenario-parameter-box-shadow: -1px -1px 0px 0px #f8f8f8 inset,
replace this with border using standard colors

2023-12-20 16:16 UTC, future-pirate-king commented on mirage/factories/organization.js
discard changes

2023-12-20 16:16 UTC, future-pirate-king commented on app/components/project-settings/view-scenario/index.hbs
> +        {{#each this.parameterList key='id' as |pm|}}
remove this `key`

2023-12-21 20:01 UTC, Yibaebi commented on app/components/project-settings/general-settings/dynamicscan-automation-settings/scenario/index.hbs
> +          </AkTypography>
There's no label argument in `AkTexrField`. Do you mean to make the tag a `label`?

2023-12-21 20:01 UTC, Yibaebi commented on app/components/project-settings/general-settings/dynamicscan-automation-settings/scenario/index.hbs
> +    @blurOverlay={{true}}
Nope. Just a personal preference. Is there a problem with this?

2023-12-21 20:39 UTC, Yibaebi commented on app/components/project-settings/view-scenario/add-parameter-form/index.hbs
> +                {{style whiteSpace='wrap' minWidth='220px'}}
It's actually not.

2024-01-03 06:38 UTC, future-pirate-king requested changes

2024-01-03 06:38 UTC, future-pirate-king commented on mirage/scenarios/default.js
discard these changes

2024-01-03 06:38 UTC, future-pirate-king commented on mirage/config.js
discard these changes

2024-01-03 10:13 UTC, future-pirate-king approved these changes

2024-01-03 10:16 UTC, merged