sidebar state stored in local storage
appknox/irene pull request #1326
Opened 2024-01-12 11:23 UTC by avzz-19

2024-01-22 11:04 UTC, future-pirate-king requested changes

2024-01-22 11:07 UTC, future-pirate-king requested changes

2024-01-22 11:07 UTC, future-pirate-king commented on app/components/home-page/organization-dashboard/index.ts
> +      JSON.stringify(this.isSidebarCollapsed)
keep value as `collapsed` and `expanded` based on state

2024-01-23 04:35 UTC, avzz-19 commented on app/components/home-page/organization-dashboard/index.ts
> +    const storedState = window.localStorage.getItem('sidebarState');
resolved internally

2024-01-23 04:42 UTC, future-pirate-king requested changes

2024-01-23 04:42 UTC, future-pirate-king commented on app/components/home-page/organization-dashboard/index.ts
> +  @service('browser/window') declare window: Window;
move service above tracked variable and add new line to separate them

2024-01-23 04:42 UTC, future-pirate-king commented on app/components/home-page/organization-dashboard/index.ts
> +    this.isSidebarCollapsed =
add new line above

2024-01-23 05:19 UTC, future-pirate-king approved these changes

2024-01-23 05:19 UTC, merged