E2E Tests for apk App Upload
appknox/irene pull request #1337
Opened 2024-02-20 23:39 UTC by Yibaebi

2024-02-22 10:38 UTC, future-pirate-king requested changes

2024-02-22 10:38 UTC, future-pirate-king commented on mirage/factories/sbom-file.ts
>  export default Factory.extend({
above object should be used

2024-02-22 10:38 UTC, future-pirate-king commented on mirage/factories/sbom-project.ts
>  export default Factory.extend({
above object should be used

2024-02-23 15:20 UTC, future-pirate-king requested changes

2024-02-23 15:20 UTC, future-pirate-king commented on app/components/upload-app/status/index.hbs
> +      aria-label='upload-app-status-loader'
can we have this in readable form ?

2024-02-23 19:52 UTC, Yibaebi commented on app/components/upload-app/status/index.hbs
> +      aria-label='upload-app-status-loader'
This isn't used. Will be removed.

2024-02-26 07:32 UTC, future-pirate-king approved these changes

2024-02-26 07:32 UTC, merged