ember test fixes for v4
appknox/irene pull request #1339
Opened 2024-02-21 13:51 UTC by avzz-19

2024-02-21 15:41 UTC, future-pirate-king requested changes

2024-02-21 15:41 UTC, future-pirate-king commented on app/components/project-settings/general-settings/github-project/index.ts
> +        err.errors[0]?.source?.pointer === '/data/attributes/riskThreshold'
why is this added ?

2024-02-21 15:41 UTC, future-pirate-king commented on app/components/security/file-actions/index.js
> +      await waitForPromise(file.save());
add new line above

2024-02-21 15:41 UTC, future-pirate-king commented on tests/integration/components/project-settings/general-settings/jira-project-test.js
> +        return new Response(200, {}, this.jiraProjects[0].toJSON());
check if response code should be `200` ? otherwise for `post` code should be `201`

2024-02-21 15:41 UTC, future-pirate-king commented on tests/unit/models/user-test.js
> +      user.set('expiryDate', new Date('25 March 2019'));
add new line above and below

2024-02-22 06:27 UTC, future-pirate-king requested changes

2024-02-22 06:27 UTC, future-pirate-king commented on app/components/security/file-actions/index.js
do we require `waitForPromise` everywhere ?

2024-02-22 06:27 UTC, future-pirate-king commented on tests/integration/components/project-settings/general-settings/github-project-test.js
>        this.server.get('/projects/:id/github', (schema, req) => {
`req` is not being used

2024-02-22 06:27 UTC, future-pirate-king commented on tests/integration/components/upload-app/via-link-test.js
> +        return this.server.create('uploadApp', data);
use `schema` param instead of server

2024-02-22 06:27 UTC, future-pirate-king commented on tests/integration/components/upload-app/via-system-test.js
> +        return this.server.create('uploadApp', data);
use `schema` param instead of server

2024-02-22 06:27 UTC, future-pirate-king commented on tests/integration/components/upload-app/index-test.js
> +      return server.create('uploadApp', data);
use `schema` param instead of server

2024-02-22 10:12 UTC, future-pirate-king requested changes

2024-02-22 10:12 UTC, future-pirate-king commented on app/components/regulatory-preference-organization/index.js
> +      this.orgPreference = await this.store.queryRecord(
need to remove import too

2024-02-22 10:12 UTC, future-pirate-king commented on app/components/sso-settings/index.js
> +      const idpMetadata = await this.store.queryRecord(
need to remove import too

2024-02-22 10:14 UTC, avzz-19 commented on app/components/regulatory-preference-organization/index.js
> +      this.orgPreference = await this.store.queryRecord(
It's used in another place, line no 81.

2024-02-22 10:15 UTC, avzz-19 commented on app/components/sso-settings/index.js
> +      const idpMetadata = await this.store.queryRecord(
It's used in other places...

2024-02-22 10:22 UTC, future-pirate-king approved these changes

2024-02-22 10:22 UTC, merged