Owasp mobile top 10 2024
appknox/irene pull request #1348
Opened 2024-03-04 13:24 UTC by avzz-19

2024-03-08 06:37 UTC, future-pirate-king requested changes

2024-03-08 06:37 UTC, future-pirate-king commented on tests/integration/components/file-details/vulnerability-analysis-details/index-test.js
> +      assert
add new line above

2024-03-08 06:37 UTC, future-pirate-king commented on tests/unit/models/owaspmobile2024-test.js
>      assert.ok(!!model);
add new line above

2024-03-08 06:37 UTC, future-pirate-king commented on translations/en.json
> -  "owasp": "OWASP",
we can keep this

2024-03-08 06:37 UTC, future-pirate-king commented on mirage/models/owaspmobile2024.ts
do we require this model ?

2024-03-08 06:37 UTC, future-pirate-king commented on app/components/file-details/vulnerability-analysis-details/index.ts
>          title: this.intl.t('owaspExpansion'),
this should also be updated

2024-03-08 06:37 UTC, future-pirate-king commented on app/adapters/owaspmobile2024.ts
need to remove old `owasp` adapter

2024-03-08 06:49 UTC, avzz-19 commented on app/adapters/owaspmobile2024.ts
There was no adapter for OWASP earlier.

2024-03-08 06:53 UTC, avzz-19 commented on mirage/models/owaspmobile2024.ts
yes, same as OWASP API TOP 10

2024-03-08 07:15 UTC, avzz-19 commented on mirage/models/owaspmobile2024.ts
removed

2024-03-08 13:17 UTC, future-pirate-king approved these changes

2024-04-01 09:10 UTC, Yibaebi requested changes

2024-04-01 09:10 UTC, Yibaebi commented on app/components/file-details/vulnerability-analysis-details/index.ts
> +        hasContent: !isEmpty(this.analysis.owaspmobile2024.toArray()),
You can use the `isOwasp2024` getter here also.

2024-04-01 09:10 UTC, Yibaebi commented on mirage/factories/owaspmobile2024.ts
> +export default Factory.extend({
Can the factory object be put in a variable? Similar to how the vulnerability factory is done. This is for the cypress tests.

2024-04-01 09:10 UTC, Yibaebi commented on tests/unit/models/owasp-test.js
>      assert.ok(!!model);
Add new line above.

2024-04-01 14:43 UTC, future-pirate-king requested changes

2024-04-02 06:11 UTC, future-pirate-king requested changes

2024-04-02 06:11 UTC, future-pirate-king commented on app/components/file-details/compliance-insights/index.hbs
> +    <AkChart
add new line above

2024-04-02 08:46 UTC, Yibaebi approved these changes

2024-04-02 08:49 UTC, merged