move organization pages to /dashboard
appknox/irene pull request #1356
Opened 2024-03-20 07:46 UTC by avzz-19

2024-04-03 06:30 UTC, future-pirate-king requested changes

2024-04-03 06:30 UTC, future-pirate-king commented on app/routes/authenticated/projects.ts
> +    const { params } = transition.to || {};
why do we require `params` here ?

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/controllers/authenticated/organization/users-test.js
this should be moved to `/authenticated/dashboard`

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/routes/authenticated/dashboard/organization-test.js
> +/* eslint-disable prettier/prettier */
remove this

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/routes/authenticated/dashboard/project-test.js
> +/* eslint-disable prettier/prettier */
remove this

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/routes/authenticated/dashboard/project-test.js
> +    var store = {
use `const` and add new line above

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/routes/authenticated/dashboard/project-test.js
> +    route.set('store', store);
add new line above and below

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/routes/authenticated/dashboard/project/files-test.js
> +/* eslint-disable prettier/prettier */
remove this

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/routes/authenticated/dashboard/project/files-test.js
> +      assert.ok(route);
add new line above

2024-04-03 06:30 UTC, future-pirate-king commented on tests/unit/routes/authenticated/organization/teams-test.js
this needs to be moved to `/authenticated/dashboard`

2024-04-08 13:01 UTC, future-pirate-king requested changes

2024-04-08 13:01 UTC, future-pirate-king commented on tests/acceptance/deprecated-routes/project-redirect-test.js
can we add test for other projects related routes that is changed ?

2024-04-09 05:09 UTC, avzz-19 commented on tests/unit/routes/authenticated/dashboard/organization/team-test.js
There is no route for this. It was changed to teams long back. Can I delete this test if not req?

2024-04-09 05:23 UTC, future-pirate-king commented on tests/unit/routes/authenticated/dashboard/organization/team-test.js
yes

2024-04-09 12:13 UTC, future-pirate-king requested changes

2024-04-09 12:13 UTC, future-pirate-king commented on app/components/file/report-drawer/sbom-reports/index.ts
> +    this.router.transitionTo(
add new line above

2024-04-09 12:13 UTC, future-pirate-king commented on app/components/marketplace/integration-list/index.ts
> -        link: '',
why is slack removed ?

2024-04-09 12:13 UTC, future-pirate-king commented on tests/acceptance/deprecated-routes/projects-redirect-test.js
> +    assert.strictEqual(
add new line above

2024-04-10 09:54 UTC, future-pirate-king approved these changes

2024-04-10 09:54 UTC, merged