security analysis details page revamp
appknox/irene pull request #1400
Opened 2024-06-13 01:33 UTC by Yibaebi

2024-06-16 11:53 UTC, future-pirate-king requested changes

2024-06-16 11:53 UTC, future-pirate-king commented on app/components/security/analysis-details/regulatory-categories/index.hbs
can we just loop through all the regulatory selects like this ?
```
{{#unless it.hidden}}
  <AkStack
    @direction='column'
    @spacing='1'
    @width='full'
    data-test-securityAnalysisDetails-regulatoryCategories='{{it.key}}'
  >
    <AkTypography
      @variant='h6'
      @fontWeight='regular'
      data-test-securityAnalysisDetails-regulatorySection-title
    >
      {{it.title}}
    </AkTypography>

    <AkSelect
      @placeholder='{{it.selectPlaceholder}}'
      @selected={{it.selectedValue}}
      @options={{it.selectOptions}}
      @onChange={{it.onSelectChange}}
      @multiple={{true}}
      class='w-full'
      data-test-securityAnalysisDetails-regulatoryCategories-select
      as |key|
    >
      {{this.getRegulatorySelectOptionLabel (array key.code key.year key.safeguard key.title key.url)}} // remove any undefined values and join by '-'
    </AkSelect>
  </AkStack>

  <AkDivider @color='dark' class='my-2' />
{{/unless}}
```

2024-06-17 22:30 UTC, Yibaebi commented on app/components/security/analysis-details/regulatory-categories/index.hbs
Updated

2024-06-17 22:30 UTC, Yibaebi commented on app/components/security/analysis-details/cvss-metrics/index.scss
> +  border: 4px solid;
It is needed for when the cvss risk is in an `untested` state.

2024-06-19 12:14 UTC, future-pirate-king approved these changes

2024-07-15 10:04 UTC, future-pirate-king approved these changes

2024-07-15 10:04 UTC, merged