Dast Automation(P1) File Details Page Update
appknox/irene pull request #1401
Opened 2024-06-14 07:53 UTC by SmitGala

2024-06-19 10:14 UTC, SmitGala commented on app/components/file-details/scan-actions/index.scss
> +  width: 240px;
Changing This

2024-06-24 09:31 UTC, future-pirate-king requested changes

2024-06-24 09:31 UTC, future-pirate-king commented on app/components/file-details/index.scss
> +  background: #faf9f9;
use `--background-light`

2024-06-24 09:31 UTC, future-pirate-king commented on app/components/file-details/index.scss
> +  padding: 0 4.285em;
change container contraint by width

2024-06-24 09:31 UTC, future-pirate-king commented on app/components/file-details/scan-actions/manual-scan/index.ts
>        [ENUMS.MANUAL.ASSESSING]: this.intl.t('inProgress'),
check this with design to refactor all to uppercase

2024-06-24 09:31 UTC, future-pirate-king commented on tests/integration/components/file-details/scan-actions-test.js
move to acceptance test

2024-06-24 09:31 UTC, future-pirate-king commented on tests/integration/components/file-details/scan-actions/api-scan-test.js
move to acceptance test

2024-06-26 09:39 UTC, future-pirate-king requested changes

2024-06-26 09:39 UTC, future-pirate-king commented on tests/integration/components/file-details/scan-actions/dynamic-scan-test.js
> +      this.file.isDynamicDone = false;
add test for other scenarios too

2024-06-28 08:42 UTC, future-pirate-king approved these changes

2024-06-28 09:03 UTC, merged