api scan full page implementation
appknox/irene pull request #1409
Opened 2024-06-27 10:58 UTC by future-pirate-king

2024-07-02 22:31 UTC, Yibaebi requested changes

2024-07-03 09:30 UTC, future-pirate-king commented on app/components/file-details/api-scan/captured-apis/index.ts
> +  setSelectedCount = task(async () => {
done

2024-07-03 09:30 UTC, future-pirate-king commented on app/components/file-details/api-scan/captured-apis/overview/index.ts
> +import CapturedApiModel from 'irene/models/capturedapi';
done

2024-07-04 08:08 UTC, Yibaebi approved these changes

2024-07-04 09:04 UTC, merged