Dast Automation General Settings Changes
appknox/irene pull request #1412
Opened 2024-06-28 15:41 UTC by SmitGala

2024-07-24 22:56 UTC, Yibaebi commented on app/components/project-settings/general-settings/device-preferences-automated-dast/index.scss
> +.version-select {
class not getting used

2024-07-24 23:00 UTC, Yibaebi commented on app/components/project-settings/general-settings/device-preferences-automated-dast/index.hbs
> +                @placeholder='Select Min OS Version'
Translate text.

2024-07-24 23:00 UTC, Yibaebi commented on app/components/project-settings/general-settings/device-preferences-automated-dast/index.hbs
> +        @placeholder={{'Select the device preference'}}
Translate text here also

2024-07-24 23:02 UTC, Yibaebi commented on app/components/project-settings/general-settings/device-preferences-automated-dast/index.ts
> +        label: 'SIM',
Translate

2024-07-24 23:04 UTC, Yibaebi commented on tests/integration/components/project-settings/general-settings/device-preferences-automated-dast-test.js
> +          console.log(schema);
Remove log

2024-07-24 23:06 UTC, Yibaebi commented on tests/integration/components/project-settings/general-settings/device-preferences-automated-dast-test.js
> +      this.server.createList('organization', 1);
Arrange `beforeEach` hook properly. Section models, server mocks and property setters appropriately.

2024-07-24 23:12 UTC, Yibaebi commented on tests/integration/components/project-settings/general-settings/device-preferences-automated-dast-test.js
> +    test('it selects min version', async function (assert) {
Test does not check if selected minOSVersion is being sent correctly via the network.

2024-07-24 23:12 UTC, Yibaebi commented on tests/integration/components/project-settings/general-settings/device-preferences-automated-dast-test.js
> +    test('it selects criteria', async function (assert) {
Test does not check if selected device criteria and selection is being sent correctly via the network.

2024-07-29 19:04 UTC, future-pirate-king requested changes

2024-07-29 19:04 UTC, future-pirate-king commented on translations/en.json
> -      "minOSVersion": "Min OS Version",
does this not impact manual scan modal ?

2024-07-30 09:24 UTC, future-pirate-king requested changes

2024-07-30 09:24 UTC, future-pirate-king commented on app/helpers/ds-automated-device-pref.ts
> +  const devicePrefernce = params[0];
typo devicePrefernce

2024-07-30 09:24 UTC, future-pirate-king commented on app/helpers/ds-manual-device-pref.ts
> +  const devicePrefernce = params[0];
typo devicePrefernce

2024-07-30 19:51 UTC, Yibaebi commented on app/models/profile.ts
> +}
For type purposes.

2024-08-08 10:49 UTC, merged