Manual scan full page implementation
appknox/irene pull request #1413
Opened 2024-07-01 05:01 UTC by future-pirate-king

2024-07-09 19:32 UTC, Yibaebi requested changes

2024-07-09 19:32 UTC, Yibaebi commented on app/components/file-details/manual-scan/index.ts
> +
Remove space here and in line 169.

2024-07-09 19:32 UTC, Yibaebi commented on app/components/file-details/manual-scan/request-access/index.ts
> +      if (err.errors && err.errors.length) {
Can we use the `parseError` utils here?

2024-07-09 19:32 UTC, Yibaebi commented on app/components/file-details/manual-scan/request-form/additional-comments/index.ts
> +import ManualscanModel from 'irene/models/manualscan';
Import models as `types`.

2024-07-09 19:32 UTC, Yibaebi commented on app/components/file-details/manual-scan/request-form/basic-info/index.ts
> +import ManualscanModel from 'irene/models/manualscan';
Add `type` to imports.

2024-07-09 19:32 UTC, Yibaebi commented on app/components/file-details/manual-scan/request-form/login-details/index.ts
> +import ManualscanModel, { UserRole } from 'irene/models/manualscan';
Add `type` to imports.

2024-07-09 19:32 UTC, Yibaebi commented on app/components/file-details/manual-scan/request-form/login-details/index.ts
> +        return role;
Add space before return.

2024-07-10 10:06 UTC, future-pirate-king commented on app/components/file-details/manual-scan/index.ts
> +    if (loginRequired) {
done

2024-07-10 10:06 UTC, future-pirate-king commented on app/components/file-details/manual-scan/index.ts
> +
done

2024-07-10 10:06 UTC, future-pirate-king commented on app/components/file-details/manual-scan/request-form/additional-comments/index.ts
> +import ManualscanModel from 'irene/models/manualscan';
done

2024-07-10 10:06 UTC, future-pirate-king commented on app/components/file-details/manual-scan/request-form/basic-info/index.ts
> +import ManualscanModel from 'irene/models/manualscan';
done

2024-07-10 10:06 UTC, future-pirate-king commented on app/components/file-details/manual-scan/request-form/login-details/index.ts
> +import ManualscanModel, { UserRole } from 'irene/models/manualscan';
done

2024-07-10 10:07 UTC, future-pirate-king commented on app/components/file-details/manual-scan/request-form/login-details/index.ts
> +        return role;
done

2024-07-10 10:13 UTC, future-pirate-king commented on app/components/file-details/manual-scan/request-access/index.ts
> +      if (err.errors && err.errors.length) {
done

2024-07-12 12:57 UTC, Yibaebi approved these changes

2024-07-12 14:47 UTC, merged