Public API documentation integration and Customization
appknox/irene pull request #1427
Opened 2024-08-06 18:39 UTC by Yibaebi

2024-08-08 07:25 UTC, future-pirate-king requested changes

2024-08-08 07:25 UTC, future-pirate-king commented on app/templates/authenticated/dashboard/public-api.hbs
> +{{page-title 'Public Api'}}
use translation here

2024-08-08 07:25 UTC, future-pirate-king commented on app/templates/authenticated/dashboard/public-api/docs.hbs
> +{{page-title 'Docs'}}
use translation here

2024-08-08 07:25 UTC, future-pirate-king commented on app/styles/_public-api.scss
can we move this to local styles

2024-08-08 22:13 UTC, Yibaebi commented on app/styles/_public-api.scss
Is there any difference or extra advantage of this? 

I think third party style overrides should exist in a single file. It's also easier to maintain, update, and possibly remove styles. I was trying to stick with the same pattern for the freshdesk style overrides.

2024-08-09 04:40 UTC, future-pirate-king commented on app/styles/_public-api.scss
advantage is we can target the styles locally then there is no chance of interference with other parts of UI
you can still keep the styles in a single file and share the file reference or through import

2024-08-15 08:53 UTC, future-pirate-king approved these changes

2024-08-15 08:53 UTC, merged