request/response finding pattern fix
appknox/irene pull request #1448
Opened 2024-09-03 17:24 UTC by future-pirate-king

2024-09-06 10:05 UTC, future-pirate-king commented on app/utils/parse-vulnerable-api-finding.ts
> +function updateSection(
can we move the function to its original location and have an updated ts doc like earlier

2024-09-06 10:05 UTC, future-pirate-king commented on app/components/public-api-docs/index.ts
> +import { waitForPromise } from '@ember/test-waiters';
group app and lib imports together

2024-09-09 05:17 UTC, Yibaebi requested changes

2024-09-09 05:17 UTC, Yibaebi commented on app/utils/parse-vulnerable-api-finding.ts
> +    (key === 'headers' && (value === '' || value === '{}')) ||
Can you put `value === '' || value === '{}'` in a variable?

2024-09-09 05:17 UTC, Yibaebi commented on app/utils/parse-vulnerable-api-finding.ts
>      if (!firstLine.startsWith('confidence:')) {
Can we merge the two if statements? 

`if (!firstLine.startsWith('confidence:') && colonIndex !== -1)`

2024-09-09 10:09 UTC, merged