global styles migration in partner dashboard
appknox/irene pull request #1450
Opened 2024-09-04 08:53 UTC by Yibaebi

2024-09-09 15:34 UTC, future-pirate-king requested changes

2024-09-09 15:34 UTC, future-pirate-king commented on app/components/partner/credit-transfer/index.scss
can we delete this file

2024-09-09 15:34 UTC, future-pirate-king commented on app/components/partner/registration-request-pending/index.hbs
> +  <AkStack @direction='column' @spacing='0.5' class='pr-2' local-class='user'>
local class user is removed

2024-09-09 15:34 UTC, future-pirate-king commented on app/components/partner/registration-request-rejected/index.hbs
> +  <AkStack @direction='column' @spacing='0.5' class='pr-2' local-class='user'>
local class user is removed

2024-09-09 15:34 UTC, future-pirate-king commented on tests/integration/components/partner/registration-request-pending-list-test.js
> +      assert.equal(header.children[3].textContent.trim(), '');
use `strictEqual` instead of `equal`

2024-09-12 10:02 UTC, Yibaebi commented on app/components/partner/credit-transfer/index.scss
It's already deleted.

2024-09-12 10:19 UTC, Yibaebi commented on tests/integration/components/partner/registration-request-pending-list-test.js
> +      assert.equal(header.children[3].textContent.trim(), '');
Done

2024-09-13 06:30 UTC, future-pirate-king approved these changes

2024-09-13 06:31 UTC, merged