Dast new api integration
appknox/irene pull request #1508
Opened 2024-12-19 06:24 UTC by future-pirate-king

2025-01-16 00:47 UTC, Yibaebi requested changes

2025-01-16 04:14 UTC, future-pirate-king commented on app/templates/authenticated/dashboard/file/dynamic-scan/scheduled-automated.hbs
> +{{page-title 'Scheduled Automated'}}
This is for internal users only and text is correct

2025-01-16 04:18 UTC, future-pirate-king commented on mirage/factories/dynamicscan.ts
> +
Just wanted this to be declared at the test level so that it is more declarative and easy to debug

2025-01-17 06:33 UTC, future-pirate-king commented on app/models/file.ts
> +  async getLastDynamicScan(
yeah it is only used only in case of scheduled scan. It does not need to be here since it is associated with a file I kept it

2025-01-17 06:35 UTC, future-pirate-king commented on app/services/dynamic-scan.ts
> +import DynamicscanModel from 'irene/models/dynamicscan';
done

2025-01-17 06:39 UTC, future-pirate-king commented on app/components/project-settings/general-settings/device-preferences-automated-dast/index.hbs
> +          >
done

2025-01-27 11:11 UTC, Yibaebi approved these changes

2025-01-28 17:26 UTC, merged