TR-249: Github action marketplace integration
appknox/irene pull request #864
Opened 2020-11-18 15:58 UTC by guganabu

2020-11-19 09:48 UTC, cosmosgenius requested changes

2020-11-19 09:48 UTC, cosmosgenius commented on app/components/marketplace-plugin-list/component.js
> +        "instructions": htmlSafe(constants.bitriseInstructions)
This is required? its bitrise?

2020-11-20 09:40 UTC, cosmosgenius approved these changes

2020-11-23 10:34 UTC, Praseetha-KR approved these changes

2020-11-23 10:34 UTC, merged